export const CONNECTION_EVENT_OPEN = Symbol("CONNECTION_EVENT_OPEN");
export const CONNECTION_EVENT_CLOSE = Symbol("CONNECTION_EVENT_CLOSE");
export const CONNECTION_EVENT_ERROR = Symbol("CONNECTION_EVENT_ERROR");
export const CONNECTION_EVENT_PROGRESS = Symbol("CONNECTION_EVENT_PROGRESS");
export const CONNECTION_EVENT_ABORT = Symbol("CONNECTION_EVENT_ABORT");
export const CONNECTION_EVENT_SUCCESS = Symbol("CONNECTION_EVENT_SUCCESS");

export const CONNECTION_STATE_INIT = Symbol("CONNECTION_STATE_INIT");
export const CONNECTION_STATE_STARTED = Symbol("CONNECTION_STATE_STARTED");
export const CONNECTION_STATE_DONE = Symbol("CONNECTION_STATE_DONE");
export const CONNECTION_STATE_CANCELED = Symbol("CONNECTION_STATE_CANCELED");
